### ISSUE TITLE
X axis and Y axis idler

### ISSUE THREAD

**Issue by markoverholser** [woolfepr/Printer-Kitten#2]
In the "X axis idler" and "Y axis idler" sections, it mentions using the "shorter bolt from bag 8" and "longer bolt from bag 8," respectively.

...I didn't notice any difference in the lengths of the bolts provided in bag 8. What's going on here?
- Kit has been changed and documentation has not caught up
- There _was_ a difference, and I just happened to luck out and put the right ones on the right places
- There _was_ a difference, and I may have put the wrong things in the wrong places, putting myself, my home, and my loved ones in peril

My idlers are stable, don't float, and spin freely, so I assume everything is alright, but I wanted to make sure there's nothing that needs to be updated in the documentation.

**Comment by woolfepr** [comment]
The threaded part of the shoulder bolts is the same length, but the shoulders should be different lengths. The shoulder and overall length of the bolt for the Y axis idler should be 4mm longer. If both of the idlers screwed in properly and don't float it sounds like you were sent the correct parts and assembled them correctly.
